config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :spaces
  root 'general#index'
  get 'general/login_popup' => 'general#login_popup', defaults: { format: 'js' }
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  has_one :space
  has_and_belongs_to_many :users
end

app/models/request.rb
class Request < ActiveRecord::Base
  has_one :space
  has_one :user
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  has_one :space
end

app/models/space.rb
class Space < ActiveRecord::Base
  has_many :resources
  has_many :ratings
  has_many :requests

  geocoded_by :address
  after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]
  has_attached_file :avatar, :styles => { :thumb => "128x128>", :icon => "32x32>" }, :default_url => "/images/:style/profile.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_many :requests
  has_and_belongs_to_many :ratings

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.avatar = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  respond_to :html, :js

  def index
    @spaces = Space.all
    @markers = Gmaps4rails.build_markers(@spaces) do |space, marker|
      marker.lat space.latitude
      marker.lng space.longitude
      marker.title space.name
      marker.infowindow render_to_string(:partial => "markerinfo", :locals => { :space => space})
    end
  end

  def login_popup
    respond_to do |format|
      format.js
    end
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]

  # GET /spaces
  def index
    @spaces = Space.all
  end

  # GET /spaces/1
  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  def create
    @space = Space.new(space_params)

    if @space.save
      redirect_to @space, notice: 'Space was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /spaces/1
  def update
    if @space.update(space_params)
      redirect_to @space, notice: 'Space was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /spaces/1
  def destroy
    @space.destroy
    redirect_to spaces_url, notice: 'Space was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def space_params
      params.require(:space).permit(:name, :description, :localization, :lat, :long, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/general/_markerinfo.html.slim
h4 = space.name
i = space.address
p = space.description

app/views/general/index.html.slim
  div class="map_spaces"
    #map_spaces class="map_spaces"
      javascript:
        var handler = Gmaps.build('Google');
        handler.buildMap({internal: {id: 'map_spaces'}}, function(){
          if(navigator.geolocation){
            navigator.geolocation.getCurrentPosition(centerMap);
          } else {
            handler.map.centerOn(new google.maps.LatLng(-10.1885145,-48.3317027));
          }
          var markers = handler.addMarkers(#{raw @markers.to_json});
          handler.bounds.extendWith(markers);
        });



        function centerMap(position){
          handler.map.centerOn(new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
        };

app/views/general/login_popup.js.erb
$('#login-modal').modal('show');
$('.modal-body').html("<%= escape_javascript(render 'devise/sessions/new') %>");

app/views/layouts/_footer.html.slim
.footer
  .i.h6.pull-right EspacoStartup 2015. Orgulhosamente criado em Palmas, Tocantins.

app/views/layouts/_navigation.html.slim
nav.navbar-default.navbar-static-side role="navigation"
  .sidebar-collapse
    ul#side-menu.nav
      li.nav-header
        .dropdown.profile-element
          span
            - if user_signed_in?
              = image_tag current_user.avatar.url(:icon), class: "img-circle"
            - else
              = image_tag 'thumb/profile.png', class: "img-circle img-small"
          a.dropdown-toggle data-toggle="dropdown" href="#"
            span.clear
              span.block.m-t-xs
                strong.font-bold = user_signed_in? ? current_user.name : 'Olá, Visitante! :)'
              - if user_signed_in?
                span.text-muted.text-xs.block.text-center
                  | Menu
                  b.caret


                ul.dropdown-menu.animated.fadeInRight.m-t-xs
                  li
                    a href="#" Minhas Solicitacoes
                  li
                    a href="#{spaces_path}" Meus espacos
                  li
                    a href="#" Estatisticas
                  li
                    a href="#" Sair

        .logo-element EspacoStartup
      li class="#{'active' if current_page?('/')}"

        = link_to "/"
          = fa_icon "sign-out", text: "Todos os Espacos"
      li class="#{'active' if current_page?('/home/minor')}"
        = link_to "#"
          = fa_icon "sign-out", text: "Melhores Espacos"
      li class="#{'active' if current_page?('/home/minor')}"
        = link_to "#"
          = fa_icon "sign-out", text: "Por Recursos"

app/views/layouts/_topnavbar.html.slim
.row.border-bottom
  nav.navbar.navbar-static-top.white-bg role="navigation" style=("margin-bottom: 0")
    .navbar-header
      a.navbar-minimalize.minimalize-styl-2.btn.btn-primary href="#"
        i.fa.fa-bars
      form.navbar-form-custom action="/" method="post" role="search"
        .form-group
          input#top-search.form-control name="top-search" placeholder=("Buscar por...") type="text"

    ul.nav.navbar-top-links.navbar-right
      li
        - if user_signed_in?
          = link_to destroy_user_session_path, method: :delete
            = fa_icon "sign-out", text: "Sair"
        - else
          = link_to general_login_popup_path, remote: true
            = fa_icon "sign-in", text: "Entrar"

.modal.fade id="login-modal" tabindex="-1" role="dialog" aria-hidden="true"
  .modal-dialog.login-modal-size
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-hidden="true"
          .span &times;
      .modal-body.center

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"

    title EspacoStartup

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "http://maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry"
    = javascript_include_tag "http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"
    = csrf_meta_tags

    /[if lt IE 9]
    = javascript_include_tag 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js', 'data-turbolinks-track' => true
  body.skin-1
    #wrapper
      = render 'layouts/navigation'
      #page-wrapper.gray-bg
        = render 'layouts/topnavbar'
        .wrapper-content.animated.fadeInRight
          = yield
      = render 'layouts/footer'

app/views/spaces/_form.html.slim
= simple_form_for(@space) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :address

  .form-actions
    = f.button :submit

app/views/spaces/edit.html.slim
h1 Editing space

== render 'form'

= link_to 'Show', @space
'|
= link_to 'Back', spaces_path

app/views/spaces/index.html.slim
h1 Meus espacos

table.table
  thead
    tr
      th
      th
      th

  tbody
    - @spaces.each do |space|
      tr
        td = link_to 'Show', space
        td = link_to 'Edit', edit_space_path(space)
        td = link_to 'Destroy', space, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Space', new_space_path

app/views/spaces/new.html.slim
h1 New space

== render 'form'

= link_to 'Back', spaces_path

app/views/spaces/show.html.slim
p#notice = notice


= link_to 'Edit', edit_space_path(@space)
'|
= link_to 'Back', spaces_path